---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexa-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: alexa-service
  replicas: 1
  template:
    metadata:
      labels:
        run: alexa-service
    spec:
      containers:
      - name: alexa-service
        image: keptnsandbox/alexa-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ALEXA_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: alexa-token
              key: webhook
        - name: ALEXA_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: alexa-token
              key: token
---
apiVersion: v1
kind: Service
metadata:
  name: alexa-service
  namespace: keptn
  labels:
    run: alexa-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: alexa-service
